config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  root 'page#index'
  mount ActionCable.server => "/cable"
  resources :chatrooms
  resources :messages, only: [] do
    get :by_group, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  after_create_commit {MessageBroadcastJob.perform_now self}
  paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def create
    @chatroom = Chatroom.new chatroom_params
    if @chatroom.save
      respond_to do |format|
        format.html{redirect_to @chatroom}
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'}
      end
    end
  end

  def show
    @chatroom = Chatroom.find params[:id]
    @message = Message.new
  end

  private
  def chatroom_params
    params.require(:chatroom).permit :topic
  end

end

app/controllers/messages_controller.rb
class MessagesController < ActionController::API
  def by_group
    messages = Message.all
    render json: messages
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">topic:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  <div id="chatroom-errors">
    
  </div>
    <ul id="chatroom-index"> 
  <% if @chatrooms.any? %>
      <%= render @chatrooms%>
  <%else %>
    </ul>
    <p>Be the first one to make a chatroom!</p>
  <% end %>
</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Create a Chatroom on a programming topic</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">topic:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/chatrooms/show.html.erb
<div>
  <h1><%= @chatroom.topic %></h1>
</div>
<div class="row border chatbox">
  <div class="panel panel-default">
    <div class="panel-body" id="messages" data-chatroom=<%=@chatroom.id%>>
      <%= render partial: 'messages/message', collection: @chatroom.messages %>
    </div>
  </div>
</div>
<%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorldActionCable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js" integrity="sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9" crossorigin="anonymous"></script>
    <style>
body {
    margin: 0 auto;
    max-width: 800px;
    padding: 0 20px;
}

.chatbox{
  width: 800px;
  height: 800px;
  overflow: scroll;
}

.message {
    border: 2px solid #dedede;
    background-color: #f1f1f1;
    border-radius: 5px;
    padding: 10px;
    margin: 10px 25px;
}

.darker {
    border-color: #ccc;
    background-color: #ddd;
}

.container::after {
    content: "";
    clear: both;
    display: table;
}

.container img {
    float: left;
    max-width: 60px;
    width: 100%;
    margin-right: 20px;
    border-radius: 50%;
}

.container img.right {
    float: right;
    margin-left: 20px;
    margin-right:0;
}

.time-right {
    float: right;
    color: #aaa;
}

.time-left {
    float: left;
    color: #999;
}
</style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%=message.content%></p>
</div>

app/views/messages/_message_form.html.erb
<textarea class="form-control" data-textarea="message" name="message[content]" id="message_content">
  </textarea>
<input type="submit" name="commit" value="send" class="btn btn-primary" data-send="message" data-disable-with="send" />

app/views/page/index.html.erb
<h1>Action Cable Example</h1>
<div id=”messages”></div>